name: Update Package Version

permissions:
  contents: read
  pull-requests: write
  packages: write

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled

jobs:
  update-version:
    name: Update Package Version
    runs-on: windows-latest
    if: contains(github.event.pull_request.labels.*.name, 'minor') || contains(github.event.pull_request.labels.*.name, 'patch')

    steps:
      - uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Determine version type
        id: version_type
        run: |
          if ($env:GITHUB_EVENT_PULL_REQUEST_LABELS -contains "minor") {
            $env:VERSION_TYPE = "minor"
          } elseif ($env:GITHUB_EVENT_PULL_REQUEST_LABELS -contains "patch") {
            $env:VERSION_TYPE = "patch"
          } else {
            $env:VERSION_TYPE = ""
          }
        shell: pwsh

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        shell: pwsh

      - name: Update package version and push tag
        if: env.VERSION_TYPE != ''
        run: |
          # Get current version from package.json
          $packageJson = Get-Content "package.json" | ConvertFrom-Json
          $currentVersion = $packageJson.version
          
          # Update package.json version
          $newVersion = npm version $env:VERSION_TYPE --no-git-tag-version
          $newVersionString = $newVersion.TrimStart('v')
          
          # Update version.ts file
          $versionTs = Get-Content "src/version.ts"
          $updatedVersionTs = $versionTs -replace 'export const packageVersion = ".*"', "export const packageVersion = `"$newVersionString`""
          $updatedVersionTs | Set-Content "src/version.ts"
          
          # Commit changes and create tag
          git add package.json src/version.ts
          git commit -m "Update version to $newVersionString"
          git tag "v$newVersionString"
          git push origin "v$newVersionString"
        shell: pwsh

      - name: Push changes
        if: env.VERSION_TYPE != ''
        run: |
          git push origin HEAD:main
        shell: pwsh